<a href="https://colab.research.google.com/github/jiminchoi2007/jimin/blob/main/____5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 5주차 실습 — Pandas (1): 표 데이터 다루기

**데이터과학과 인공지능 · 2026-2학기**

---

영상을 보면서 직접 따라 실행하세요.

> 시작 전에 **파일 → 드라이브에 사본 저장** 을 먼저 누르세요.

### 지난주 복습

4주차에서 배운 것 중 이번 주에 계속 쓰는 건 세 가지입니다.

| 지난주에 배운 것 | 이번 주에 이렇게 활용니다 |
|---|---|
| `import pandas as pd` | 매 노트북 첫 줄에 고정으로 등장 |
| `.무엇()` 은 시키는 일, `.무엇` 은 가진 정보 | `df.head()` vs `df.shape` |
| `딕셔너리["키"]` 로 값 꺼내기 | `df["메뉴"]` 로 열 꺼내기 |

지난주 마지막에 `df["가격"] * df["수량"]` 한 줄로 전체 계산이 되는 걸 봤습니다. 그게 어떻게 가능한지가 오늘의 내용입니다.

### 오늘의 목표

- 표(DataFrame)와 열(Series)이 무엇인지 구분한다
- **데이터가 어디서 왔고 무엇이 빠져 있는지** 묻는 습관을 들인다
- **변수의 종류**(범주형·이산형·연속형)를 구분한다
- 원하는 **열**을 꺼내고, 조건에 맞는 **행**을 골라낸다
- **글자가 담긴 열**도 다룬다
- 정렬하고, 새 열을 만들고, 저장한다

### 📣 지난주 과제 피드백을 반영했습니다

여러분이 적어준 "어려웠던 점"을 읽고 세 가지를 추가했습니다.

- **0절**: 괄호 치트시트와 `NameError` 해결법 (가장 많이 나온 질문이었습니다)
- **3.2절**: 점 표기법 다시 보기 (두 번째로 많았습니다)
- **10절 FAQ**: 여러분이 실제로 적어준 질문들에 대한 답

막히면 언제든 0절과 10절로 돌아오세요.

---
## 0. 시작하기 전에 — 지난주에 가장 많이 막혔던 것들  

4주차 과제 피드백을 읽어보니 **코드 내용보다 그 주변에서 막힌 경우**가 많았습니다. 이 절에서 먼저 정리하고 갑니다.

### 0.1. 시작 전 체크 세 가지

**① 드라이브에 사본 저장**

상단 메뉴 **파일 → 드라이브에 사본 저장**. 이걸 안 하면 고친 내용이 저장되지 않습니다.

**② LMS에서 받은 파일이 드라이브에 안 보일 때**

LMS에서 다운로드한 파일은 **구글 드라이브가 아니라 내 컴퓨터**에 저장됩니다. 드라이브에서 열려면

1. 드라이브에서 좌측 상단 **+ 신규 → 파일 업로드**
2. 내 컴퓨터의 **다운로드** 폴더에서 `.ipynb` 파일 선택

또는 코랩에서 **파일 → 노트 업로드**로 바로 올려도 됩니다.

**③ 코랩 AI 자동완성 끄기 (권장)**

코랩이 코드를 미리 써주는 기능 때문에 "직접 생각할 기회가 없다"는 의견이 있었습니다. 끄는 방법은

> **도구 → 설정 → AI 어시스턴트** 에서 코드 자동완성 관련 항목 해제

### 0.2. 괄호와 따옴표 치트시트 — 막히면 여기로 돌아오세요

지난주 가장 많이 나온 질문입니다. **"언제 `()`, 언제 `[]`, 언제 `{}` 를 쓰나요?"**

외우려 하지 말고, **각 기호가 하는 일이 다르다**는 것만 기억하세요.

| 기호 | 이름 | 하는 일 | 예시 |
|---|---|---|---|
| `( )` | 소괄호 | **일을 시킬 때** (함수·메서드 호출) | `print(...)`, `len(...)`, `df.head()` |
| `[ ]` | 대괄호 | **① 리스트 만들기 ② 꺼내기** | `[1, 2, 3]`, `점수들[0]`, `df["메뉴"]` |
| `{ }` | 중괄호 | **① 딕셔너리 만들기 ② f-문자열 안에서 변수 넣기** | `{"이름": "김고려"}`, `f"{나이}살"` |
| `" "` | 큰따옴표 | **글자라는 표시** | `"아메리카노"` |

한 문장으로 줄이면 이렇습니다.

> **소괄호는 "해줘", 대괄호는 "꺼내줘", 중괄호는 "여기에 끼워넣어"**

아래 셀을 실행하면서 눈으로 확인해 보세요.

In [ ]:
# ( ) — 일을 시킨다
print("안녕하세요")        # print에게 보여달라고 시킴
print(len("안녕하세요"))   # len에게 길이를 세달라고 시킴

# [ ] — 만들거나 꺼낸다
점수들 = [88, 92, 75]      # 리스트를 만든다
print(점수들[0])           # 0번째를 꺼낸다

# { } — 딕셔너리를 만들거나, f-문자열에 끼워넣는다
학생 = {"이름": "김고려"}   # 딕셔너리를 만든다
print(학생["이름"])        # 꺼낼 때는 [ ] 를 쓴다!

나이 = 20
print(f"저는 {나이}살입니다")   # f-문자열 안에 끼워넣는다

안녕하세요
5
88
김고려
저는 20살입니다

**헷갈리기 쉬운 지점 하나.** 딕셔너리는 `{ }` 로 **만들지만**, 값을 **꺼낼 때는 `[ ]`** 를 씁니다. 만드는 기호와 꺼내는 기호가 다릅니다.

```python
학생 = {"이름": "김고려"}    # 만들 때: 중괄호
학생["이름"]                 # 꺼낼 때: 대괄호
```

오늘 배울 `df["메뉴"]` 도 **꺼내는** 동작이라 대괄호입니다.

### 0.3. `NameError` — 셀 실행 순서 이야기

지난주 과제에서 **가장 많이 나온 오류**입니다.

```
NameError: name 'df' is not defined
```

코드를 아무리 봐도 멀쩡한데 이 오류가 납니다. 왜일까요?

**코랩은 위에서부터 순서대로 실행해야 합니다.** 셀을 하나 실행하면 그 결과(변수)가 컴퓨터 메모리에 저장되고, 아래 셀에서 그걸 꺼내 씁니다. 위 셀을 건너뛰면 **아래 셀이 쓸 재료가 없는 상태**가 됩니다.

직접 확인해 봅시다. 아래 두 셀 중 **두 번째 것을 먼저** 실행해 보세요.

In [ ]:
# ① 이 셀을 먼저 실행하면 아래 셀이 작동합니다
좋아하는메뉴 = "아메리카노"

In [ ]:
# ② 위 셀을 실행하지 않고 이것만 실행하면 NameError가 납니다
print(좋아하는메뉴)

아메리카노

`NameError` 가 났다면 위 셀을 실행하고 다시 해보세요. 이번엔 잘 됩니다.

### `NameError` 가 나면 할 일

**1. 위 셀들을 순서대로 실행했는지 확인**

셀 왼쪽에 `[1]`, `[2]` 처럼 번호가 붙습니다. 번호가 없으면 **아직 실행하지 않은 셀**입니다. 건너뛴 게 없는지 보세요.

**2. 오타 확인**

`메뉴` 와 `menu` 는 다른 이름입니다. `수량` 과 `수랑` 도 다릅니다. 지난주에 실제로 나온 사례입니다.

**3. 런타임이 끊겼는지 확인**

브라우저를 닫았다가 다시 열거나, 오래 방치하면 **지금까지 만든 변수가 전부 사라집니다.** 파일은 남아 있지만 메모리는 비워집니다.

이때는 당황하지 말고 **런타임 → 모두 실행** 을 누르세요. 처음부터 끝까지 다시 실행됩니다. 중간부터만 다시 하려면 **런타임 → 이전 셀 실행** 입니다.

> ### 오늘 학하다 막히면
>
> 1. 빨간 글씨의 **마지막 줄**을 읽는다
> 2. `NameError` 면 → 위 셀부터 다시 실행
> 3. 그래도 안 되면 → **런타임 → 모두 실행**
> 4. 여전히 안 되면 → 코드 전체와 오류 메시지를 통째로 복사해서 AI에게 묻거나 Q&A에 올린다

---
## 1. 데이터를 만나기

먼저 실습 데이터를 만듭니다. 아래 셀은 **그냥 실행**하세요.

In [ ]:
# 설정 셀 — 그냥 실행만 하세요 (이 코드는 몰라도 됩니다)
import random
random.seed(26)

메뉴정보 = {
    "아메리카노": ("커피", 4500), "카페라떼": ("커피", 5000),
    "바닐라라떼": ("커피", 5500), "콜드브루": ("커피", 5000),
    "녹차라떼": ("논커피", 5500), "초코라떼": ("논커피", 5500),
    "자몽에이드": ("논커피", 6000), "복숭아아이스티": ("논커피", 4500),
}
요일표 = ["월", "화", "수", "목", "금"]
좋은후기 = [
    "맛이 깔끔하고 좋았어요", "직원분이 친절하셨습니다", "자리가 넓어서 공부하기 좋아요",
    "가격 대비 양이 넉넉합니다", "향이 진하고 맛있어요", "분위기가 조용해서 좋네요",
]
보통후기 = [
    "무난한 맛입니다", "그냥 평범했어요", "나쁘지 않지만 특별하지도 않아요",
    "가격은 적당한 편", "다시 올지는 모르겠네요",
]
나쁜후기 = [
    "대기 시간이 너무 길었어요", "맛이 생각보다 밍밍합니다", "자리가 없어서 서서 마셨어요",
    "가격에 비해 아쉬웠습니다", "주문이 잘못 나왔어요", "대기가 길고 시끄러웠어요",
]

행들 = ["날짜,요일,매장,메뉴,분류,가격,수량,결제수단,평점,후기"]
for 주 in range(3):
    for i, 요일 in enumerate(요일표):
        날짜 = f"2026-03-{2 + 주 * 7 + i:02d}"
        for 매장 in ["안암점", "정문점"]:
            for 메뉴 in random.sample(list(메뉴정보), 3):
                분류, 가격 = 메뉴정보[메뉴]
                수량 = random.randint(5, 45)
                결제 = random.choice(["카드", "현금", "간편결제"])
                평점 = random.choices([1, 2, 3, 4, 5], weights=[3, 7, 20, 40, 30])[0]
                풀 = 좋은후기 if 평점 >= 4 else (보통후기 if 평점 == 3 else 나쁜후기)
                후기 = random.choice(풀)
                행들.append(f"{날짜},{요일},{매장},{메뉴},{분류},{가격},{수량},{결제},{평점},{후기}")

with open("cafe_sales_full.csv", "w", encoding="utf-8") as f:
    f.write("\n".join(행들))

print(f"cafe_sales_full.csv 생성 완료 — 총 {len(행들) - 1}행")

cafe_sales_full.csv 생성 완료 — 총 90행

### 데이터 설명서를 먼저 읽습니다

코드를 치기 전에 할 일이 있습니다. **이게 무슨 데이터인지 확인하는 것**입니다.

분석을 배울 때 가장 흔한 실수가, 주어진 표를 하늘에서 떨어진 사실로 취급하는 것입니다. 모든 데이터는 **누군가가 어떤 목적으로 어떤 방식으로** 모은 것이고, 그 과정에서 반드시 무언가가 빠질 수도 있음을 기억해주세요.

> **데이터 설명서**
>
> - **이름**: 안암·정문 카페 3주간 판매 기록 (가상 데이터)
> - **수집 주체**: 카페 본사 운영팀
> - **수집 목적**: 메뉴 구성과 재고 발주 계획 수립
> - **수집 방법**: 매장 POS(결제 단말기) 시스템에서 자동 집계
> - **기간**: 2026년 3월 2일 ~ 3월 20일 (평일만)
> - **단위**: 1행 = 하루 한 매장에서 한 메뉴가 팔린 집계
> - **평점·후기**: 영수증 QR로 접속한 고객이 자율적으로 남긴 것

이 설명만으로도 **빠져 있는 것들**이 보입니다.

- **주말이 없습니다.** 평일만 모았으니 주말 매출 패턴은 알 수 없습니다.
- **안 팔린 메뉴는 없습니다.** 품절이라 못 산 사람, 메뉴판에 없어서 안 시킨 사람은 이 표에 흔적이 없습니다.
- **POS에 안 찍힌 건 없습니다.** 직원 시음, 서비스로 나간 음료, 현금 미등록 건은 빠집니다.
- **후기는 자율 제출입니다.** 보통 **아주 만족했거나 아주 불만인 사람**이 남깁니다. 그냥 괜찮았던 다수는 안 남깁니다.

마지막 항목은 특히 중요합니다. 여러분이 설문이나 리뷰 데이터를 다룰 때 거의 항상 마주치는 문제입니다. 심리학에서 말하는 **자기선택 편향**이고, 역사 자료를 다룰 때 "남아 있는 기록만 읽게 되는" 문제와 같은 구조입니다.

**여러분의 전공에서 훈련받는 "이 자료는 누가 왜 남겼는가"라는 질문이, 데이터 분석에서도 그대로 첫 번째 질문입니다.**

이제 불러옵니다. 노트북에서 가장 먼저 치는 두 줄입니다.

In [ ]:
import pandas as pd

df = pd.read_csv("cafe_sales_full.csv")
df

            날짜 요일   매장     메뉴   분류    가격  수량  결제수단  평점              후기
0   2026-03-02  월  안암점   콜드브루   커피  5000  32  간편결제   4    직원분이 친절하셨습니다
1   2026-03-02  월  안암점   초코라떼  논커피  5500  35    카드   5     향이 진하고 맛있어요
2   2026-03-02  월  안암점   카페라떼   커피  5000  37    카드   4    직원분이 친절하셨습니다
3   2026-03-02  월  정문점  자몽에이드  논커피  6000   6  간편결제   5    직원분이 친절하셨습니다
4   2026-03-02  월  정문점   초코라떼  논커피  5500  14    카드   3       가격은 적당한 편
..         ... ..  ...    ...  ...   ...  ..   ...  ..             ...
85  2026-03-20  금  안암점   콜드브루   커피  5000  42    카드   5  가격 대비 양이 넉넉합니다
86  2026-03-20  금  안암점  바닐라라떼   커피  5500  41    현금   5    직원분이 친절하셨습니다
87  2026-03-20  금  정문점   콜드브루   커피  5000  35  간편결제   3        무난한 맛입니다
88  2026-03-20  금  정문점   녹차라떼  논커피  5500  43    현금   5    직원분이 친절하셨습니다
89  2026-03-20  금  정문점   카페라떼   커피  5000  35    현금   5   분위기가 조용해서 좋네요

[90 rows x 10 columns]

지난주 배운 걸로 읽어보면 이렇습니다.

- `pd.read_csv(...)` → pd에게 CSV를 읽어달라고 **시킴** (괄호 있음 = 메서드)
- `df = ...` → 그 결과에 `df` 라는 이름표를 붙임

`df` 는 DataFrame의 줄임말이고, 거의 모든 사람이 이 이름을 씁니다.

---
## 2. DataFrame과 Series — 표와 열

Pandas에는 두 가지 그릇이 있습니다.

| 이름 | 모양 | 비유 |
|---|---|---|
| **DataFrame** | 2차원 — 행과 열이 있는 **표 전체** | 엑셀 시트 한 장 |
| **Series** | 1차원 — **열 하나** | 엑셀의 A열 하나 |

In [ ]:
print(type(df))
print(type(df["메뉴"]))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

Series는 4주차의 **리스트와 비슷하지만 더 똑똑한 것**입니다. 리스트는 전체에 2를 곱하려면 for문이 필요했지만, Series는 그냥 곱하면 됩니다.

In [ ]:
# 리스트는 이렇게 하면 원하는 결과가 안 나옵니다
수량_리스트 = [10, 20, 30]
print(수량_리스트 * 2)

# Series는 각 값에 곱해집니다
print(df["수량"].head(3) * 2)

[10, 20, 30, 10, 20, 30]
0    64
1    70
2    74
Name: 수량, dtype: int64

리스트는 `* 2` 가 **이어붙이기**, Series는 **각 값에 곱하기**였습니다.

이 차이가 Pandas를 쓰는 가장 큰 이유입니다. 수천 행도 반복문 없이 한 줄로 계산됩니다.

---
## 3. 표 훑어보기와 변수의 종류

### 3.1. 처음 만난 데이터 파악하기

새 데이터를 받으면 분석 전에 **무엇이 들어있는지부터** 봅니다.

In [ ]:
df.head()      # 앞에서 5줄 (기본값 5)

           날짜 요일   매장     메뉴   분류    가격  수량  결제수단  평점            후기
0  2026-03-02  월  안암점   콜드브루   커피  5000  32  간편결제   4  직원분이 친절하셨습니다
1  2026-03-02  월  안암점   초코라떼  논커피  5500  35    카드   5   향이 진하고 맛있어요
2  2026-03-02  월  안암점   카페라떼   커피  5000  37    카드   4  직원분이 친절하셨습니다
3  2026-03-02  월  정문점  자몽에이드  논커피  6000   6  간편결제   5  직원분이 친절하셨습니다
4  2026-03-02  월  정문점   초코라떼  논커피  5500  14    카드   3     가격은 적당한 편

In [ ]:
print(df.shape)      # (행 개수, 열 개수) — 속성이라 괄호 없음
print(df.columns)    # 열 이름들 — 속성

(90, 10)
Index(['날짜', '요일', '매장', '메뉴', '분류', '가격', '수량', '결제수단', '평점', '후기'], dtype='object')

`df.shape` 가 `(90, 10)` 이면 **90행 10열**입니다. 항상 행이 먼저입니다.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      90 non-null     object
 1   요일      90 non-null     object
 2   매장      90 non-null     object
 3   메뉴      90 non-null     object
 4   분류      90 non-null     object
 5   가격      90 non-null     int64
 6   수량      90 non-null     int64
 7   결제수단    90 non-null     object
 8   평점      90 non-null     int64
 9   후기      90 non-null     object
dtypes: int64(3), object(7)
memory usage: 7.2+ KB

`info()` 가 알려주는 것은 세 가지입니다.

1. **총 몇 행인가**
2. **각 열에 값이 몇 개 차 있는가** (`non-null count`) — 빈칸이 있는지 알 수 있습니다
3. **각 열의 자료형이 무엇인가** (`Dtype`)

| Dtype | 뜻 | 4주차 용어로 |
|---|---|---|
| `int64` | 정수 | `int` |
| `float64` | 실수 | `float` |
| `object` 또는 `str` | 글자 | `str` |

**가격 열이 숫자가 아니라 글자로 잡혀 있으면 계산이 안 됩니다.** 4주차에 `"20" + "5"` 가 `205` 가 됐던 그 문제입니다. 실제 업무 데이터에서는 `1,500` 처럼 쉼표가 들어있어서 글자로 읽히는 일이 아주 흔합니다. 그래서 `info()` 를 먼저 봅니다.

### $$$ 점 표기법 다시 보기 — 괄호가 있을 때와 없을 때

지난주 피드백에서 **두 번째로 많이 나온 질문**입니다. 방금 `df.shape` 에는 괄호가 없고 `df.info()` 에는 있었습니다. 왜 다를까요?

4주차에 배운 규칙은 이것이었습니다.

> **괄호가 있으면 "해줘"(메서드), 없으면 "알려줘"(속성)**

이 비유 자체는 잘 전달됐는데, **실제 코드에서 어느 쪽인지 바로 알아보기 어렵다**는 의견이 많았습니다. 그래서 세 가지로 나눠 보겠습니다.

### ① 속성 vs 메서드 — 이미 있는가, 만들어야 하는가

| | 속성 (괄호 없음) | 메서드 (괄호 있음) |
|---|---|---|
| 뜻 | **이미 가지고 있는 정보** | **지금 계산해서 만들어야 하는 것** |
| 예시 | `df.shape`, `df.columns`, `math.pi` | `df.head()`, `df.info()`, `math.sqrt(16)` |

`df.shape` 는 표를 만들 때 이미 정해진 크기입니다. 꺼내 보기만 하면 됩니다.
`df.head()` 는 "앞에서 몇 줄 잘라줘"라는 **작업**입니다. 몇 줄인지도 말해줘야 합니다.

`math.pi` 에 괄호가 없는 이유도 같습니다. 원주율은 **이미 정해진 값**이지 계산할 게 아닙니다. 반면 `math.sqrt(16)` 은 16을 받아서 **지금 계산**해야 합니다.

**구분이 안 될 때는 그냥 둘 다 해보세요.** 틀리면 오류가 알려줍니다.

In [ ]:
# 속성에 괄호를 붙이면 어떻게 될까요? 일부러 틀려봅시다
df.shape()

TypeError: 'tuple' object is not callable

마지막 줄: `TypeError: 'tuple' object is not callable`

→ **"이건 시킬 수 있는 게 아닌데요"** 라는 뜻입니다. `callable` 은 "불러서 시킬 수 있는"이라는 뜻입니다.

이 오류가 뜨면 **괄호를 빼면 됩니다.** 반대로 괄호를 빼야 할 걸 안 뺐을 때는 결과가 이상하게 나옵니다.

In [ ]:
print(df.shape)       # 괄호 없이: 올바른 결과
print(df.head)        # 괄호 빼먹었을 때: 이상한 게 나옵니다

`df.head` 만 쓰면 "이 기능은 여기 있습니다"라는 안내만 나옵니다. **실행은 안 된 것**입니다. 괄호를 붙여야 실제로 작동합니다.

### ② `len()` 은 왜 점을 안 찍나

지난주에 나온 질문입니다. `"안녕".upper()` 는 점을 찍는데 `len("안녕")` 은 왜 안 찍을까요?

| | 모양 | 뜻 |
|---|---|---|
| **함수** | `len(대상)` | 누구에게나 쓸 수 있는 **독립된 도구** |
| **메서드** | `대상.기능()` | **그 대상에만 붙어 있는** 기능 |

`len()` 은 문자열, 리스트, 딕셔너리 어디에나 쓸 수 있는 공용 도구입니다. 그래서 괄호 안에 대상을 넣습니다.
`.upper()` 는 **문자열에만** 있는 기능입니다. 리스트에는 대문자 변환이 없습니다. 그래서 문자열에 붙여서 씁니다.

In [ ]:
# 함수: 대상을 괄호 안에 넣는다
print(len("안녕하세요"))
print(len([1, 2, 3]))
print(sum([1, 2, 3]))

# 메서드: 대상에 점을 찍어 붙인다
print("안녕하세요".upper())
print("안녕 하세요".split())

### ③ 점이 연달아 나올 때 — `df.isna().sum()`

가장 많이 헷갈린다고 적어준 부분입니다. 읽는 방법은 하나입니다. **왼쪽부터 차례로, 앞의 결과에 다시 시킨다.**

```
df . isna() . sum()
│     │        │
│     │        └─ 그 결과를 세어줘
│     └────────── 빈칸인지 표시해줘
└──────────────── 표에게
```

단계별로 쪼개서 실행하면 바로 보입니다.

In [ ]:
# 1단계: 글자 열의 길이를 재면?
단계1 = df["메뉴"].str.len()
print(단계1.head())

In [ ]:
# 2단계: 그 결과에 다시 평균을 시키면?
단계2 = 단계1.mean()
print(단계2)

In [ ]:
# 두 단계를 한 줄로 붙인 것이 바로 이것입니다
print(df["메뉴"].str.len().mean())

### 3.2. 변수의 종류 — 저장 형식과 의미는 다르다

여기가 오늘 가장 중요한 개념입니다.

`info()` 가 알려준 건 **컴퓨터가 어떻게 저장하고 있는지**입니다. 그런데 분석할 때 필요한 건 **그 값이 무엇을 의미하는지**입니다. 이 둘은 자주 어긋납니다.

통계에서 쓰는 변수 구분은 이렇습니다.

| 종류 | 설명 | 평균을 내도 되나 |
|---|---|---|
| **명목형** (범주형) | 이름일 뿐 순서가 없음 | 안됨 |
| **순서형** | 순서는 있지만 간격이 일정하지 않음 | 조심 |
| **이산형** | 셀 수 있는 숫자 (정수) | 가능 |
| **연속형** | 잴 수 있는 숫자 (소수 가능) | 가능 |

우리 데이터에 적용하면 이렇습니다.

| 열 | 저장 형식 | 변수 종류 | 메모 |
|---|---|---|---|
| `날짜` | 글자 | 시간 | 지금은 글자. 날짜형으로 바꿔야 계산 가능 (6주차) |
| `요일` | 글자 | 명목형 | 월·화·수에 순서가 있다고 볼 수도 있음 |
| `매장`, `메뉴`, `분류`, `결제수단` | 글자 | 명목형 | 평균이 의미 없음 |
| `평점` | **정수** | **순서형** | 숫자지만 조심해야 함 |
| `수량` | 정수 | 이산형 | 반 잔은 팔 수 없음 |
| `가격` | 정수 | 명목형에 가까움 | 메뉴마다 고정값이라 사실상 메뉴의 꼬리표 |
| `후기` | 글자 | **비정형 텍스트** | 표에 담겨 있지만 구조가 없음 |

**`평점` 을 보세요.** `int64` 로 저장돼 있으니 Python은 평균을 계산해 줍니다. 그런데 그 평균이 의미가 있을까요?

별 1개와 2개의 차이가, 별 4개와 5개의 차이와 **같은 크기라고 할 수 있나요?** 사람마다 별점을 주는 기준도 다릅니다. 그래서 평점 평균 3.7은 계산은 되지만 해석에는 주의가 필요합니다.

**`가격` 도 마찬가지입니다.** 숫자지만 메뉴마다 정해진 값이라, 가격 평균은 "메뉴 목록의 평균"이지 "손님이 낸 평균 금액"이 아닙니다. 손님 기준 평균을 구하려면 수량으로 가중해야 합니다.

**컴퓨터는 숫자면 무조건 평균을 내 줍니다. 그게 말이 되는지는 사람이 판단해야합니다.**

In [ ]:
# 계산은 됩니다. 하지만 의미가 같을까요?
print("평점 평균:", df["평점"].mean())
print("가격 평균:", df["가격"].mean())
print("수량 평균:", df["수량"].mean())

### ⏸ 직접 해보세요 (1)

1. `df` 의 앞에서 **7줄**을 보세요
2. 이 표가 몇 행 몇 열인지 출력하세요
3. 위 세 개의 평균 중 **가장 해석하기 안전한 것**은 무엇이라고 생각하나요? 아래 주석에 한 줄로 적어보세요.

In [ ]:
# TODO 1. 앞에서 7줄


# TODO 2. 행/열 개수


# 3. 가장 해석하기 안전한 평균은? 이유는?
# 답:

---
## 4. 열 선택하기

### 열 하나 - 대괄호 하나

4주차의 딕셔너리와 똑같은 모양입니다.

In [ ]:
df["메뉴"]

### 열 여러 개 - 대괄호 두 개

여러 열은 **열 이름들을 리스트로 묶어서** 넣습니다. 그래서 대괄호가 두 겹이 됩니다.

In [ ]:
df[["메뉴", "가격", "수량"]]

| 코드 | 결과 |
|---|---|
| `df["메뉴"]` | **Series** (열 하나) |
| `df[["메뉴"]]` | **DataFrame** (열 하나짜리 표) |
| `df[["메뉴", "가격"]]` | **DataFrame** (열 두 개) |

안쪽 대괄호는 "리스트", 바깥 대괄호는 "꺼내라"입니다. `df[ ["메뉴", "가격"] ]` 로 띄어서 보면 이해가 쉽습니다.

In [ ]:
print(df["수량"].sum())      # 총합
print(df["수량"].mean())     # 평균
print(df["수량"].max())      # 최댓값

### value_counts(): 각 값이 몇 번 나오는가

**명목형 변수에서 가장 유용한 메서드**입니다. 빈도표를 만들어 줍니다.

In [ ]:
df["메뉴"].value_counts()

In [ ]:
df["평점"].value_counts()

`value_counts()` 는 데이터를 처음 볼 때 거의 반드시 돌려봅니다. 어떤 값들이 있는지, 오타는 없는지 한눈에 보이기 때문입니다.

결과에 `"커피"` 와 `"커 피"` 가 따로 나온다면 오타가 섞인 겁니다. 다음 주 정제 수업에서 다룹니다.

> ###  생각해볼 질문
>
> 위에서 아메리카노가 가장 많이 **기록된** 메뉴로 나왔습니다. 그런데 이게 "가장 인기 있는 메뉴"라고 말할 수 있을까요?
>
> 이 표에는 **팔린 것만** 들어 있습니다. 품절이라 못 산 사람, 메뉴판에 없어서 못 시킨 사람은 어디에도 없습니다. 만약 어떤 메뉴가 늘 품절이었다면, 그 메뉴는 "인기가 없어서" 기록이 적은 게 아닙니다.
>
> 데이터에 **있는 것**을 세는 일은 쉽습니다. **없는 것**을 알아채는 게 어렵습니다. 답을 적을 필요는 없지만, 자기 도메인 데이터를 다룰 때 이 질문을 꼭 한 번 해보세요.

### 멈추고 직접 해보세요 (2)

1. `매장` 열과 `결제수단` 열만 꺼내서 앞 5줄을 보세요
2. `결제수단` 의 값들이 각각 몇 번 나오는지 세어보세요
3. `분류` 의 빈도를 세어보세요

In [ ]:
# TODO 1.


# TODO 2.


# TODO 3.

---
## 5. 행 선택하기 — 조건으로 골라내기

오늘의 **가장 중요한 부분**입니다. 엑셀의 필터 기능에 해당합니다.

### 1단계: 조건을 쓰면 True/False가 나온다

In [ ]:
df["수량"] > 30

숫자가 아니라 `True` / `False` 가 90개 나왔습니다. **각 행에 대해 "이 조건에 맞니?"를 물어본 결과**입니다.

### 2단계: 그 결과를 대괄호에 넣으면 True인 행만 남는다

In [ ]:
df[df["수량"] > 30]

처음에는 `df` 가 두 번 나오는 게 어색합니다. 이렇게 읽으면 됩니다.

```
df[ df["수량"] > 30 ]
└┬┘ └──────┬──────┘
 표에서     이 조건에 맞는 행만
```

### 글자 조건도 됩니다

같은지 비교할 때는 **등호를 두 개** 씁니다. `=` 하나는 "값을 넣어라"였습니다(4주차).

In [ ]:
df[df["분류"] == "커피"].head()

### 조건 두 개 이상 — `&` 와 `|`

- `&` : 그리고 (둘 다 만족)
- `|` : 또는 (하나라도 만족)

**각 조건을 반드시 괄호로 감싸야 합니다.** 안 감싸면 오류가 납니다. 가장 흔한 실수입니다.

In [ ]:
df[(df["매장"] == "안암점") & (df["수량"] > 30)]

In [ ]:
df[(df["평점"] <= 2) | (df["수량"] < 10)].head()

### isin(): 여러 값 중 하나인가

`|` 를 계속 이어 쓰면 길어집니다. 값이 여러 개면 `isin()` 이 깔끔합니다.

In [ ]:
df[df["메뉴"].isin(["아메리카노", "콜드브루", "카페라떼"])].head()

### 골라낸 결과를 변수에 담기

In [ ]:
안암점 = df[df["매장"] == "안암점"]

print(안암점.shape)
print(안암점["수량"].sum())

### ⏸ 직접 해보세요 (3)

1. `분류` 가 `"논커피"` 인 행만 골라서 몇 행인지 출력하세요
2. `정문점` 이면서 `평점` 이 5인 행을 골라 앞 5줄을 보세요
3. 결제수단이 `"카드"` 또는 `"간편결제"` 인 행이 몇 개인지 출력하세요

In [ ]:
# TODO 1.


# TODO 2.


# TODO 3.

---
## 6. 정렬하기, 그리고 loc / iloc

`sort_values()` 로 특정 열 기준 정렬을 합니다.

In [ ]:
df.sort_values("수량", ascending=False).head()   # 큰 것부터

`ascending=False` 가 "내림차순"입니다. 기본값은 `True`(작은 것부터)입니다.

> **주의**: `sort_values()` 는 정렬된 **사본**을 돌려줄 뿐 원본 `df` 는 그대로입니다. 결과를 계속 쓰려면 변수에 담아야 합니다. Pandas 메서드는 대부분 이렇습니다. "실행했는데 왜 안 바뀌었지" 싶을 때 이걸 의심하세요.

In [ ]:
정렬본 = df.sort_values("수량", ascending=False)

print(정렬본.head(3)["수량"].tolist())    # 정렬됨
print(df.head(3)["수량"].tolist())        # 원본은 그대로

### loc 와 iloc — 읽을 수 있을 정도만

| | 기준 | 예시 |
|---|---|---|
| `iloc` | **순서 번호** | `df.iloc[0]` → 첫 번째 행 |
| `loc` | **이름표** | `df.loc[0, "메뉴"]` → 0번 행의 메뉴 |

실제로는 조건 필터링(5절)을 훨씬 많이 씁니다. 지금은 눈에 익히는 정도면 충분합니다.

In [ ]:
print(df.iloc[0]["메뉴"])        # 첫 번째 행의 메뉴
print(df.loc[0, "메뉴"])         # 같은 결과
print(df.iloc[0:3].shape)        # 0~2번 (끝 제외)
print(df.loc[0:3].shape)         # 0~3번 (끝 포함!)

---
## 7. 새 열 만들기

없는 열 이름에 값을 넣으면 **새 열이 생깁니다.**

In [ ]:
df["매출"] = df["가격"] * df["수량"]
df.head()

반복문 없이 90행이 한 번에 계산됐습니다.

조건에 따라 값을 넣는 것도 자주 씁니다.

In [ ]:
df["인기도"] = "보통"
df.loc[df["수량"] > 30, "인기도"] = "인기"

df

> ### 생각해볼 질문
>
> 방금 한 줄로 **"인기"라는 범주를 세상에 만들어냈습니다.**
>
> 그런데 기준이 왜 30인가요? 제가 그냥 정한 숫자입니다. 29잔 팔린 음료는 왜 "보통"인가요? 기준을 25로 바꾸면 결과가 달라지고, 그 표를 받아 본 사람은 다른 결정을 내릴 겁니다.
>
> 측정하고 분류하는 일은 중립적이지 않습니다. **어디서 선을 긋는가가 결과를 만듭니다.** "저소득층", "고위험군", "활성 사용자" 같은 말도 전부 누군가가 어딘가에 선을 그어 만든 것입니다.
>
> 여러분이 보고서에 범주를 만들 때는, **그 기준을 어떻게 정했는지 반드시 밝히세요.**

### ⏸ 직접 해보세요 (4)

1. `매출` 기준 **큰 것부터** 정렬해서 앞 5줄을 보세요
2. `만족` 이라는 새 열을 만드세요. 평점이 4 이상이면 `"만족"`, 아니면 `"불만족"`
3. 만든 열의 빈도를 세어보세요
4. 2번에서 **평점 3을 "불만족"에 넣은 것이 타당한지** 한 줄로 적어보세요

In [ ]:
# TODO 1.


# TODO 2.


# TODO 3.


# 4. 평점 3을 불만족으로 묶은 것에 대한 생각:
# 답:

---
## 8. 글자가 담긴 열 다루기

여러분이 앞으로 만날 데이터에는 **숫자가 아니라 글자**가 들어 있는 경우가 많습니다. 설문의 자유응답, 상품 리뷰, 기사 본문, 인터뷰 전사본 같은 것들입니다.

이런 걸 **비정형 데이터**라고 합니다. 행과 열로 딱 떨어지지 않는 자료입니다.

좋은 소식은, **표의 한 열에 담기기만 하면 지금까지 배운 방법을 거의 그대로 쓸 수 있다**는 것입니다. 우리 데이터의 `후기` 열로 해보겠습니다.

In [ ]:
df["후기"].head(10)

### .str 액세서라 — 글자 열 전용 도구

글자 열에는 `.str` 을 붙이면 글자 전용 기능들이 열립니다. **4주차에 배운 문자열 메서드와 이름이 같습니다.**

| 4주차에 배운 것 | Pandas에서 |
|---|---|
| `"안녕".replace("안", "반")` | `df["후기"].str.replace("안", "반")` |
| `"안녕 하세요".split()` | `df["후기"].str.split()` |
| `len("안녕")` | `df["후기"].str.len()` |

차이는 하나입니다. 4주차엔 **글자 하나**에 적용했고, 지금은 **열 전체(90개)** 에 한 번에 적용됩니다.

In [ ]:
# 후기 길이 재기
df["후기길이"] = df["후기"].str.len()

df[["후기", "후기길이"]].head()

In [ ]:
print("가장 긴 후기 길이:", df["후기길이"].max())
print("평균 후기 길이:", df["후기길이"].mean())

### str.contains(): 특정 단어가 들어있는가

**글자 열에서 가장 많이 쓰는 기능**입니다. 조건 필터링(5절)과 똑같이 쓰면 됩니다.

In [ ]:
df["후기"].str.contains("대기").head(10)

5절에서 본 True/False가 또 나왔습니다. 그러면 대괄호에 넣으면 되겠죠.

In [ ]:
df[df["후기"].str.contains("대기")]

`"대기"` 가 들어간 후기만 골라냈습니다. **질적 자료에서 특정 주제가 언급된 사례를 찾는 작업**이 바로 이겁니다.

몇 건인지, 전체의 몇 퍼센트인지도 바로 셀 수 있습니다.

In [ ]:
대기언급 = df[df["후기"].str.contains("대기")]

print("대기 언급 건수:", len(대기언급))
print("전체 대비 비율:", len(대기언급) / len(df) * 100, "%")
print("대기 언급 후기의 평균 평점:", 대기언급["평점"].mean())
print("전체 평균 평점:", df["평점"].mean())

마지막 두 줄을 비교해 보세요. 대기를 언급한 후기의 평점이 전체보다 낮다면, **대기 시간이 불만의 원인일 가능성**을 시사합니다.

다만 **시사할 뿐 증명하지는 않습니다.** 짚어야 할 게 두 가지입니다.

첫째, **건수가 너무 적습니다.** 몇 건밖에 안 되는 사례로 평균을 내면 한두 개가 통째로 결과를 흔듭니다. "차이가 보인다"와 "차이가 있다"는 다른 말입니다. 이 간극을 다루는 방법은 통계학 과목에서 배우고, 이 수업에서는 **앞의 표현까지만** 씁니다.

둘째, **방향을 알 수 없습니다.** 대기가 길어서 평점이 낮은 건지, 원래 불만인 사람이 이유를 찾다가 대기를 언급한 건지는 이 데이터로 구분되지 않습니다.

### 키워드를 여러 개 세어보기

In [ ]:
키워드들 = ["맛", "대기", "친절", "가격", "자리"]

for 키워드 in 키워드들:
    건수 = df["후기"].str.contains(키워드).sum()
    print(f"{키워드}: {건수}건")

4주차에 배운 for문이 여기서 쓰였습니다. `True` 는 1, `False` 는 0으로 취급되어서 `.sum()` 이 곧 "참인 개수"가 됩니다.

### 단어 수 세기

In [ ]:
df["단어수"] = df["후기"].str.split().str.len()

df[["후기", "단어수"]].head()

`split()` 으로 쪼갠 뒤 `len()` 으로 개수를 셌습니다. 점이 연달아 나오는 구조인데, **왼쪽부터 차례로** 읽으면 됩니다(4주차).

> ### 생각해볼 질문
>
> 지금 우리는 `"맛"` 이라는 글자가 들어있는지로 세고 있습니다. 그런데 이 방식으로는
>
> - `"맛없어요"` 와 `"맛있어요"` 가 **둘 다 "맛" 언급**으로 세어집니다
> - `"대기"` 를 언급하지 않고 `"오래 기다렸다"` 라고 쓴 후기는 **빠집니다**
> - 반어법이나 비꼬는 표현은 전혀 잡히지 않습니다
>
> 단순 키워드 검색의 한계입니다. 이걸 넘어서려면 **의미를 이해하는 도구**가 필요한데, 그게 13주차에 다룰 생성형 AI입니다. 후기 90건을 LLM에게 주고 주제별로 분류시키는 방법을 배웁니다.
>
> 다만 그때도 핵심 질문은 같습니다. **AI가 분류한 결과를 어떻게 믿을 수 있는가.**

### ⏸ 직접 해보세요 (5)

1. `"친절"` 이 들어간 후기만 골라서 몇 건인지 출력하세요
2. 그 후기들의 **평균 평점**을 출력하세요
3. 후기 길이가 **15자 이상**인 행만 골라 앞 5줄을 보세요

In [ ]:
# TODO 1.


# TODO 2.


# TODO 3.

---
## 9. 저장하기, 그리고 실제 파일 불러오기

### 저장

`index=False` 를 꼭 붙이세요. 안 붙이면 쓸데없는 번호 열이 같이 저장됩니다.

In [ ]:
df.to_csv("내가_만든_결과.csv", index=False, encoding="utf-8-sig")
print("저장 완료")

`encoding="utf-8-sig"` 는 **엑셀에서 열었을 때 한글이 안 깨지게** 하는 설정입니다. 한국에서 작업할 때는 거의 항상 붙이세요.

왼쪽 폴더 아이콘에서 오른쪽 클릭하면 다운로드됩니다.

---

### 실제 파일은 이렇게 불러옵니다 (읽어만 두세요)

**방법 1 — 직접 업로드**

```python
from google.colab import files
업로드 = files.upload()          # 파일 선택 창이 뜸

df = pd.read_csv("파일이름.csv")
```

간단하지만 **런타임이 끊기면 파일이 사라집니다.**

**방법 2 — 인터넷 주소에서 바로 읽기**

```python
df = pd.read_csv("https://주소/데이터.csv")
```

**방법 3 — 엑셀 파일**

```python
df = pd.read_excel("데이터.xlsx")
df = pd.read_excel("데이터.xlsx", sheet_name="2026년")   # 특정 시트
df = pd.read_excel("데이터.xlsx", skiprows=3)            # 위 3줄 건너뛰기
```

공공기관 엑셀은 맨 위에 제목과 설명이 몇 줄 있어서 열 이름이 깨지는 경우가 많습니다. 그때 `skiprows=` 를 씁니다.

---

### 자주 나는 오류 두 가지

**1. `FileNotFoundError`** → 그 이름의 파일이 없습니다. 왼쪽 폴더 아이콘에서 **철자와 확장자**를 확인하세요. `data.csv` 와 `data (1).csv` 는 다른 파일입니다.

**2. 한글이 깨질 때**

```python
df = pd.read_csv("데이터.csv", encoding="cp949")
```

한국에서 만들어진 CSV는 `cp949` 또는 `euc-kr` 인 경우가 많습니다.

---

> ###  7주차 준비 안내
>
> 여러분이 3주차에 고른 **도메인 데이터를 실제로 불러오는 작업은 7주차 실시간 수업**에서 같이 합니다. 인코딩이나 파일 형식 문제는 그때 해결하면 되니 지금 애쓰지 않으셔도 됩니다.
>
> 다만 그 전까지 두 가지만 해두세요.
>
> 1. **데이터 파일을 미리 내려받아 두세요.** CSV나 엑셀이면 좋습니다.
> 2. **이 데이터를 누가, 무엇을 위해, 어떻게 모았는지** 한 문단으로 정리해 두세요. 1절에서 본 데이터 설명서처럼요. 중간 프로젝트 보고서의 첫 번째 항목이 바로 이것입니다.

---
## 10. 확인 문제 (LMS 제출)

**제출 방법**: 끝까지 푼 뒤 **파일 → 다운로드 → .ipynb 다운로드** 로 저장해 LMS에 올리세요.

맞고 틀림으로 점수를 매기지 않습니다. 막힌 곳을 파악해 7주차에 다시 설명하기 위한 용도이니, **틀려도 되니 비워두지 말고** 제출하세요.

---

### 문제 1

`df` 에서 `메뉴`, `매장`, `매출` 세 열만 꺼내 앞 5줄을 출력하세요.

In [ ]:
# 문제 1
# '가격'과 '수량'을 곱해 '매출' 열을 새로 만듭니다
df['매출'] = df['가격'] * df['수량']

# 필요한 세 열만 선택해 앞에서 5줄을 출력합니다
df[['메뉴', '매장', '매출']].head(5)

      메뉴   매장      매출
0   콜드브루  안암점  160000
1   초코라떼  안암점  192500
2   카페라떼  안암점  185000
3  자몽에이드  정문점   36000
4   초코라떼  정문점   77000

### 문제 2

`분류` 가 `"커피"` 이면서 `매출` 이 100000원 이상인 행이 몇 개인지 출력하세요.

In [ ]:
# 문제 2
df[(df["분류"] == "커피") & (df["매출"] >= 100000)].shape[0]

33

### 문제 3

후기에 `"가격"` 이 언급된 행만 골라서, **건수**와 **평균 평점**을 출력하세요.

In [ ]:
# 문제 3

### 문제 4

아래 코드는 오류가 납니다. **오류 이름과 이유**를 적고 고치세요.

```python
df[df["분류"] == "커피" & df["수량"] > 30]
```

### 문제 5 — 데이터를 의심하기 (제출 필수)

1절의 **데이터 설명서**를 다시 읽어보세요.

이 데이터로 **"우리 카페에서 가장 인기 있는 메뉴는 아메리카노다"** 라고 결론 내린다면, 어떤 점을 더 확인해야 할까요? **빠져 있을 수 있는 정보**를 한 가지 이상 적어주세요.

정답은 없습니다. 여러분 전공에서 자료를 다룰 때 하는 질문을 그대로 해보시면 됩니다.

> (여기에 적으세요)

---

### 문제 6 — 어디서 막혔나요 (제출 필수)

헷갈린 항목에 표시해 주세요.

- [0] DataFrame과 Series의 차이
- [ ] 대괄호 한 겹과 두 겹의 차이
- [0] 변수의 종류 (명목형·순서형·이산형·연속형)
- [ ] 조건 필터링에서 `df` 가 두 번 나오는 구조
- [0] `&` 와 괄호
- [ ] `.str` 붙이는 글자 열 다루기
- [ ] 사본을 돌려준다는 말의 뜻
- [ ] 기타:

AI에게 질문했다면 **어떤 질문을 했고 답이 도움이 되었는지**도 적어주세요.

> (여기에 적으세요)

---

수고하셨습니다.

다음 주 6주차에는 **같은 카페 데이터의 지저분한 버전**을 드립니다. 빈칸과 중복, 오타가 섞인 데이터를 정리하고, 그룹별로 요약하는 법을 배웁니다.